export const Events = {
  ROOM_CREATE: 'room:create',
  ROOM_JOIN: 'room:join',
  ROOM_UPDATE: 'room:update',
  ROOM_SEARCH: 'room:search',
  ROOM_GET: 'room:get',
  PLAYER_UPDATE: 'player:update',
  PLAYER_SEARCH: 'player:search',
  PLAYER_UPDATE_ROLE: 'player:update:role',
  PLAYERS_UPDATE: 'players:update',
  GAME_START: 'game:start',
  GAME_ROUND_START: 'game:round:start',
  GAME_ROUND_CONTINUE: 'game:round:continue',
  GAME_ROUND_END: 'game:round:end',
  GAME_UPDATE_STATE: 'game:update:state',
  GAME_UPDATE_SCORES: 'game:update:scores',
  GAME_TURN_END: 'game:update:turn',
  GAME_JOIN: 'game:join',
  GAME_END: 'game:end',
  GAME_RESET: 'game:reset',
  DISCONNECTING: 'disconnecting',
};
