export const GameStates = {
  LOBBY: 'LOBBY',
  SELECTION_ONE: 'SELECTION',
  SELECTION_TWO: 'SELECTION_TWO',
  GUESSING_ONE: 'GUESSING_ONE',
  GUESSING_TWO: 'GUESSING_TWO',
  SCORING: 'SCORING',
  PRE_SCORING: 'PRE_SCORING',
  GAME_END: 'GAME_END',
};
