name: Production Build

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
          cache: 'yarn'

      - name: Install TypeScript
        run: npm install typescript

      - name: Docker build
        run: docker build . -t 978544736059.dkr.ecr.eu-west-2.amazonaws.com/hints-and-tints-backend

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Configure AWS Credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Docker login
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin 978544736059.dkr.ecr.eu-west-2.amazonaws.com
  
      - name: Docker push
        run: docker push 978544736059.dkr.ecr.eu-west-2.amazonaws.com/hints-and-tints-backend
